services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postdba
      - POSTGRES_DB=flaskrestapidb
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: